version: "3"
services:
  app-server:
    image: backend
    container_name: backend
    tty: true
    restart: always
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - mern-app

  frontend:
    image: ui
    container_name: ui
    build:
      context: ./ui
      args:
        API_BASE_URL: http://192.168.99.100:8080/
    ports:
      - "4200:80"
    depends_on:
      - app-server
    stdin_open: true
    tty: true
    restart: always
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
